### ISSUE TITLE
Annotation button? 

### ISSUE THREAD

**Issue by oldjove** [alberti42/obsidian-plugins-annotations#1]
Nice plugin. I've long thought that something like this would be useful. One comment though is that, by adding the text to every plugin it adds to the overall "noise" and screen real-estate that the plugins take up. I'm wondering if it's also possible to have an annotation button on the right, along with the "settings" and other buttons. I think this would help to make the plugin feel more organically part of the interface. Not sure if it's technically possible of course -- just a suggestion.

**Comment by alberti42** [comment]
Thanks for the feedback and I am glad that you find the plugin useful. I am not sure if I understand your request. What is  overall "noise" and screen real-estate? I show you in the screenshot how it looks like on my screen:

![Bildschirmfoto 2024-06-20 um 10 43 48](https://github.com/alberti42/obsidian-plugins-annotations/assets/61808/4f057416-5c31-4c76-a133-8ac9ac161882)

Does your system look differently?

**Comment by oldjove** [comment]
Thanks. The interface looks fine when there are annotations for plugins, as in your screenshot. What I mean is when plugins don't yet have a personal annotations, as is the case with most of mine right now:

![image](https://github.com/alberti42/obsidian-plugins-annotations/assets/47560940/d7783176-829e-4ceb-8add-e13849a28fe8)

There's still the "Personal annotation" heading and the "Add your personal comment about ... " text. Personally, I find this adds a bit of clutter to the interface and also makes it harder to differentiate between plugins that do and don't have annotations. So I was wondering if there's some way to reduce that -- e.g. by having an "annotation" button next to settings etc, and the "personal annotation" heading/text only appearing when there's an actual annotation for that plugin. 

Just a thought. I still find the plugin very nice as it is.

**Comment by oldjove** [comment]
Sounds great. Thanks.

**Comment by alberti42** [comment]
I have released a new version 1.1.0 that hides the annotations when these are empty. The user can hover on empty annotations to add personal comments. You are welcome to try it out.

**Comment by oldjove** [comment]
Thanks! I'll check it out.

**Comment by alberti42** [comment]
I close this issue because I think there are many options now, including the possibility to hide placeholders where no annotation exists yet.
