### ISSUE TITLE
Feature request: CSS snippet or way to add end matter in order to "surround" label text. Bonus, a trick I found to make annotations bold/italic

### ISSUE THREAD

**Issue by ksdavidc** [alberti42/obsidian-plugins-annotations#11]
I tried to set up a css snippet, because (unlike some who want the annotation to be less noticeable) I want the annotations to be more noticeable.

I started actually by noticing that if I put asterisks at the end of my labels, e.g. `this is a label: **`, and then put asterisks at the end of my note: `this is my note**`, I get a lovely bold note that stands out nicely: "this is a label: **this is my note**"

But this has the "flaw" that I have to add the final "**".

FR 1: is there a way to add a post-label end matter text that gets put at the end of the note. One could do this, for example, by implementing a ${plugin_notecontent} placeholder for the actual annotation.

For example, now one might have: "[[admin/Plugins/${plugin_name}| ${plugin_name}]]: **" as the label. I wonder if one could do:

`This is my label for [[admin/Plugins/${plugin_name}| ${plugin_name}]]: **${plugin_notecontent}** this stuff goes at the end.`
where `** this stuff goes at the end.` would be the end matter, and `${plugin_notecontent}` would hold the actual annotation.

FR 2: CSS snippet. Actually, this is already working. I had problems making it work because of the other problems, but now that I check, it seems to be working, e.g.

```
.plugin-comment {
    margin: 5px;
    background: maroon;
}

.plugin-comment-annotation {
    padding: 5px;
    background: blue;
}
```

I guess my question would be, are there any particular css values or suggestions that could be useful to know?

**Comment by alberti42** [comment]
Yes, it is possible to customize the style by using your own .css file. I can help you with this customization. However, you could already have a look whether the following solution suits you. Here is an example where you do not need the symbol `**` (used in markdown for bold) and you can achieve much more control with the following:

```
<span style="font-weight: bold; font-size:30px">[[00 Meta/Installed plugins/${plugin_name} | ${plugin_name}]]&nbsp;</span>
```

**Comment by alberti42** [comment]
This is how it looks on my computer with font-size:30px as in the example above:

![Uploading Bildschirmfoto 2024-08-20 um 00.10.17.jpg…]()

**Comment by ksdavidc** [comment]
> This is how it looks on my computer with font-size:30px as in the example above:
> 
> ![Bildschirmfoto 2024-08-20 um 00 10 17](https://private-user-images.githubusercontent.com/61808/359276556-c52bc6aa-d447-46df-9f72-adc8a7a1b57d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxMTA4NTQsIm5iZiI6MTcyNDExMDU1NCwicGF0aCI6Ii82MTgwOC8zNTkyNzY1NTYtYzUyYmM2YWEtZDQ0Ny00NmRmLTlmNzItYWRjOGE3YTFiNTdkLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE5VDIzMzU1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTliOWVjMmZmOGNlZDc3NWQyMjBhYTA1YzhkOTRkOWExZDZlNjU4ZTVjMGY3Y2M1Y2Q4MmFhYWQwOWUwN2NkY2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aJva6iwVK1rBOEOlHIllp6asgCGyZwtJg8OG-rHe79U)

1. Interesting that you are putting html within markdown and it still works, which is not how Obsidian usually works.

<img width="423" alt="Screenshot 2024-08-20 at 8 43 13 AM" src="https://github.com/user-attachments/assets/69cc6641-275b-4c08-ade9-924009b4f8fa">



3. This now seems to be connected to https://github.com/alberti42/obsidian-plugins-annotations/issues/5#issuecomment-2297460505. I noticed that if do a search, then instead of being blue it is red. using the css I showed above
```
.plugin-comment {
    margin: 5px;
    background: maroon;
}

.plugin-comment-annotation {
    padding: 5px;
    background: blue;
}
```
, and is no longer editeable. Editeability returns if I close settings and return (it flashes red, then turns blue).

https://github.com/user-attachments/assets/1dd65a7f-14d4-4d1e-be2f-b550b336c179

4. Unless I misunderstand, the code you gave was good for the case of editing just the label via the plugin settings. But I want the whole label + annotation to be css-ed as well. To use the html/markdown approach with the contents, it would need tot be done to each annotation, and would not work across the board.

**Comment by alberti42** [comment]
Yes, you can use CSS customization on your own. I am not planning to support it in the future, since there is already a way for advanced users to implement the desire changes.

Add CSS snippet in the Appearance pane:

![Bildschirmfoto 2024-08-20 um 09 43 20](https://github.com/user-attachments/assets/246fca19-0ba1-48c6-a099-43b5f6a03add)

Add this content to the CSS snippet:

![Bildschirmfoto 2024-08-20 um 09 43 35](https://github.com/user-attachments/assets/82735912-c366-47ab-b0dd-d1c94e87a9f2)

```
.plugin-comment-annotation {
    color: red;
    font-size: 30px;

}
```

This is how it will look like (quite visible 😂):

![Bildschirmfoto 2024-08-20 um 09 43 05](https://github.com/user-attachments/assets/22a2f099-4fe3-4d28-9707-7207a60ab65f)

Let me know if it works for you.

**Comment by alberti42** [comment]
And if it is important for you to change the settings from Obsidian, you can use `Style Settings` plugin, which allows you to modify your own CSS with menus of this kind (just an example from my vault):

![Bildschirmfoto 2024-08-20 um 09 47 31](https://github.com/user-attachments/assets/6214d579-16bf-4169-8154-ff31b02138f5)

**Comment by ksdavidc** [comment]
Andrea: I want to apologize for just suddenly dumping a mess of random collision data at you. I can imagine it would have been a bit burdensome. You caught me off guard with your speedy attention...I suppose I felt the need to reply hastily as well. I certainly didn't mean to push you to support things you aren't intending to. I was trying to describe what appeared to be a multi-faceted (and not fully understood on my part) situation as briefly yet accurately as I could. I should have made it clearer that I was already using snippets and the other "advanced" methods you mentioned. I am not a quantum physicist, but I know my way around a Pauli matrix. My problem was not there, but that using snippets was revealing something about several related effects that I am not sure you intended to have in your code. I was really asking:

1. Are there are any other css selectors specific to the code that are not discernible from using the inspector.
2. Is it acceptable to you that annotations not be editeable upon search. This is a minor issue, but it may not be intended, and may indicate an issue elsewhere.
3. Duplicate icons are also not really that important as far as functionality, but I suspected you didn't intend it to be that way and would want to know it was happening. I do appreciate that you found a solution. 
4. If I do use the "advanced" or recommended methods, is there a simple way to access the content of the annotation, not just either the whole thing (.plugin-comment-annotation or .plugin-comment), or the labels (via the settings).
5. If you had ${plugin-content} that would be one way that might fall within your framework.
6. TBH adding asterisks at the end, aka sticking with markdown and css, is clunky, but seems preferable and more elegant than hard-coding span or html tags into the mix, so I will probably make do with that.  
7. I am trying to intrude as minimally as possible into the internals of the plugin with all this. You, of course, know your code better than I do, and any suggestions or conjectures on my part are purely born of ignorance (in fact to the extent done, I have been clearly wrong as to what was going on) and in no way intended to say "this is what you should do". 

Thank you for the fixes you made and the attention you gave to this. Don't worry about me. I am insignificant. If things turn out to be important later, much later, then do as you see fit. It's a good plugin and I really like it.

p.s. well, I have one suggestion, from a pet peeve of mine. It would be nice to be able to see/edit the annotations on the individual plugin settings pages, since that is usually where I can see the information I want to record. That would be chef's kiss. But probably something you never plan to do.

**Comment by alberti42** [comment]
Dear David, thank you very much for the detailed and high-quality feedback.

I may be able to reply to the different points in the following days.

Regarding point 2, you found a bug where annotations could be edited only if they existed already! I believe I could fix it and I issued a new release. Now you can also add new annotations where there were none when restricting the number of plugins using the search functionality.

**Comment by ksdavidc** [comment]
> Dear David, thank you very much for the detailed and high-quality feedback.
> 
> I may be able to reply to the different points in the following days.
> 
> Regarding point 2, you found a bug where annotations could be edited only if they existed already! I believe I could fix it and I issued a new release. Now you can also add new annotations where there were none when restricting the number of plugins using the search functionality.

I just tried the new update and adding annotations w/ search works beautifully. Thank you!
