### ISSUE TITLE
Is it possible to display the plugin's GitHub repository just below each installed plugin in the settings pane?

### ISSUE THREAD

**Issue by exam-ple** [alberti42/obsidian-plugins-annotations#13]
Now, it's inconvenient to open the GitHub repository for a installed plugin. 
If each installed plugin's GitHub repository is just below the plugin information in the settings pane, it will be more convenient. 
Maybe this amazing plugin can make it possible :blush:
Thanks for your great plugin  :heart:

**Comment by alberti42** [comment]
Thanks!

Great idea. It is definitely possible and I will implement it. I also want to add a setting so that the user can decide whether to show this info or not.

**Comment by alberti42** [comment]
Done! Check version 1.7.0.

At the end it was much more complicated than what anticipated.

The repositories are not exposed in Obsidian. Obsidian itself loads them from `https://raw.githubusercontent.com/obsidianmd/obsidian-releases/master/community-plugins.json`.

Moreover, I had to detect changes in the appearance mode, light or dark, and react on those changes to have nice icons.

Hopefully I did not bring in any new bug.

**Comment by exam-ple** [comment]
Awesome! Thank you sooooo much🌹Icons are so cute❤

By the way, is it possible to display each plugin's annotations and GitHub repository in the "community plugins" browse pane?

**Comment by alberti42** [comment]
Yes, it is possible. I think it should be straightforward.. however, I should give thoughts how to display it in the preference pane. I think on the top with a small heading title "Personal annotation:" which is set by the user. But then I noticed that not all plugins comply with this style code, which is the recommended by Obsidian. Some old plugins have graphics that differ very much. These days, they do not allow you to publish plugins with inconsistent style compared to the standard. But back then yet. So in these cases I need to invent something to separate the annotation from the rest.. but it won't look so consistent... mainly because these other plugins are not following any consistent style code.

**Comment by exam-ple** [comment]
I mean here(community plugins → browse): 

![240828-090720](https://github.com/user-attachments/assets/242bea8c-8949-43c4-b303-691aa43aab0b)

**Comment by alberti42** [comment]
Ok. I had previously understood in the preference pane of each respective plugin...

Yes, this addition should be possible, but I cannot promise it. There is not much space in the small boxes to show annotations. For the github icon, yes, for sure ...

I would have to look how involved/simple it is.

**Comment by alberti42** [comment]
Feature was implemented.

**Comment by ksdavidc** [comment]
YOu say this feature was implemented, but I am not seeing it. I can see the github link in the community plugins page

<img width="1030" height="256" alt="Image" src="https://github.com/user-attachments/assets/993506e7-ed05-4c15-a3ae-2b9030299654" />

but not in the browse community  plugins page, as suggested
<img width="678" height="438" alt="Image" src="https://github.com/user-attachments/assets/0bb7b631-10cc-4f5d-9194-995ebe544fb4" />

It would be nice if the browse community plugins page could also (optionally) show the annotations...(see #23 for related suggestion for individual settings pages.)

**Comment by alberti42** [comment]
Yes they changed the API in Obsidian. I need to fix it. Sorry!

**Comment by alberti42** [comment]
I release a new version 1.7.12: https://github.com/alberti42/obsidian-plugins-annotations/releases

It should now work again. Could you test it? Thanks!
