### ISSUE TITLE
Doesn't work on mobile 

### ISSUE THREAD

**Issue by CoderWithaBoner** [alberti42/obsidian-plugins-annotations#2]
![GitHub issue](https://github.com/alberti42/obsidian-plugins-annotations/assets/137457943/9471a7c3-5c95-4ba5-81ed-e2c64bc9390d)

I see the text that I'm supposed to press on to write on. However, a single press opens the plugin in the "community browse" section, which is frustrating because it keeps happening accidentally. But I figured out that when I hold and press on the text it shows me the caret, but not the keyboard; and I'm just there watching my Caret trying to figure out how to get my keyboard to show. 

Similar to the previous issue #1 I think there needs to be a button,  not for the same reason (though I like his reason) but to make it at least work on mobile, I think? That way you'd be fixing two issues at once?

Suggestion: I think it would be too good if you made it to have its own menu of plugins, similar to "Plugin manager." I think it would be cleaner, if it has its own options, like: "filtering, arranging, hiding, favouriting" 

Edit: **Partially fixed.** As i took the screenshot with the caret, I closed obsidian, and went on GitHub. When I went back to obsidian, and out of nowhere, the keyboard showed up; So basically, the temporary fix is: hold on the text, for the caret to show. Close obsidian and open again.

**Comment by alberti42** [comment]
I am sorry to hear that you have to:

> So basically, the temporary fix is: hold on the text, for the caret to show. Close obsidian and open again.

I did not see this bug before. Now, I have realized that if you had already annotations, perhaps because you made them using a desktop version of Obsidian, it is very easy to edit them from a mobile, but if there is no annotation, it does not show the keyboard.

My suggestion for now is to use a desktop version to enter your annotations. You can then easily modify them from your mobile.

This bug will be fixed in the next weeks, but I cannot promise in the next days.

And yes, having a setting page can help to manage other options. However, I wanted to give the user the possibility to effortlessly edit annotations directly from where the plugins are officially maintained. I wanted to avoid that the setting page of my plugin becomes a replacement for the Obsidian pane where now community plugins are maintained...

But let's collect ideas and then try to make an implementation of a meaningful setting page.

**Comment by CoderWithaBoner** [comment]
> I did not see this bug before. Now, I have realized that if you had already annotations, perhaps because you made them using a desktop version of Obsidian, it is very easy to edit them from a mobile, but if there is no annotation, it does not show the keyboard.




You are totally correct. But it's not a bug that is frustrating for the user, it works perfectly. It's not a terrible bug. It just needs to be clarified. sorry if there is misunderstanding didn't use desktop to annotate. I used mobile, using the method I stated, in the previous comment and this one. 




> My suggestion for now is to use a desktop version to enter your annotations. You can then easily modify them from your mobile.




I found a good way for mobile. The whole problem is that the keyboard doesn't show up the first time editing an annotation, only the caret does, which means that once it is shown, I can simply scroll while the keyboard is shown and write.







 For clarification:




1. I don't need to reopen obsidian, every time I edit an annotation, only the first time when the caret shows up; I close obsidian and reopen it again; Once the keyboard is shown, I just keep adding annotations while the keyboard is shown. 




2. When I said that, I close and reopen obsidian, for the keyboard to show up. I didn't mean to literally close the whole app; I meant simply pressing the home button and opening it again. Similar to desktop, assuming you only have a virtual keyboard to write on, when you click to add an annotation, the virtual keyboard doesn't show up (assuming, also, that you have no way of opening the virtual keyboard except it being automatic, like mobile), but the caret does, so you simply minimize the app and reopen it, then it shows up, and then you simply continue using that virtual keyboard to edit other annotations; however, once the keyboard is not visible, you have to repeat the same method.
















> This bug will be fixed in the next weeks, but I cannot promise in the next days.




I think the best thing for you to do for now, at least, is to clarify how it should be used on mobile until it is fixed, to avoid uninstallations, because I did uninstall it at first, but I liked the plugin a lot, so I doubted myself, so I opened the issue while having Obsidian in the background. When  I opened it, voila, the keyboard showed up.













> And yes, having a setting page can help to manage other options. However, I wanted to give the user the possibility to effortlessly edit annotations directly from where the plugins are officially maintained. I wanted to avoid that the setting page of my plugin becomes a replacement for the Obsidian pane where now community plugins are maintained...




Understandable. Some people may like it, but adding a feature that only serves certain people (who want that feature) would only create enemies against it. Keeping it simple, ig, is best for all; also less work for you.




> But let's collect ideas and then try to make an implementation of a meaningful setting page.




An easy feature would be, adding custom colors. Helping to differentiate between the plugin description and the annotation—but a better one—is adding custom text formats, like bold or something.




Thanks for your response.

**Comment by alberti42** [comment]
Bug fixed!

I released a new version 1.0.12 that should have the bug fixed. Check the change log:

# Changelog

## [1.0.12] - 2024-06-23

### Bug fixes
- **Mobile Optimization**:
  - Resolved the issue where the caret and keyboard were not shown when clicking on placeholder text in mobile devices.
  - Clicking on a placeholder text now selects the entire text, allowing users to easily start typing.

### Bug Fixes
- **Annotation Deletion**:
  - Fixed an issue where annotations were not correctly deleted when the text was removed.

**Comment by alberti42** [comment]
Thanks a lot for the many ideas:

> Great idea I had, which I think I am easy feature, would be: adding custom colors. Helping to differentiate between the plugin description and the annotation—but a better one—is adding custom text formats, like bold or something.

Styles are easy to add. You can already now change your style if you use custom .css. I could provide more hints. The other possibility to write styled text is a bit more demanding because it requires an HTML editor. However, I could imagine allowing the user to enter HTML in the field. But non experienced users might find it too tricky. So this could be an advanced opion which could be enabled in the setting pane (which does not exist yet).

**Comment by CoderWithaBoner** [comment]
> Bug fixed!
> 
> I released a new version 1.0.12 that should have the bug fixed. I would appreciate if you can give feedback. Check the change log:
> 
> # Changelog
> 
> ## [1.0.12] - 2024-06-23
> 
> ### Bug fixes
> - **Mobile Optimization**:
>   - Resolved the issue where the caret and keyboard were not shown when clicking on placeholder text in mobile devices.
>   - Clicking on a placeholder text now selects the entire text, allowing users to easily start typing.
> 
> ### Bug Fixes
> - **Annotation Deletion**:
>   - Fixed an issue where annotations were not correctly deleted when the text was removed.



Brilliant. Nice idea to get around the issue. Now it selects the words, even when there is no annotation. Thanks a lot, it works perfectly.
