### ISSUE TITLE
Feature request: Add links to markdown files [[Plugin - Annotator]]

### ISSUE THREAD

**Issue by merlinuwe** [alberti42/obsidian-plugins-annotations#3]
Thanks for your useful plugin.

Is it possible to insert markdown links like [[this note about a plugin]] to the annotations?

I allready have notes for my plugins and it would be comfortable to reach them from here:

![image](https://github.com/alberti42/obsidian-plugins-annotations/assets/4138869/c8a876c4-69d4-41b3-9dbd-5d707f0e364b)

**Comment by alberti42** [comment]
Thanks! I think it is a good idea. For sure it is possible. I need to 
think how to implement it.

**Comment by alberti42** [comment]
In the version 1.2.0, you can now add Markdown and HTML text. Links to Markdown notes work! The instructions are provided in the setting pane of the plugin. I am glad to hear your feedback.

**Comment by merlinuwe** [comment]
Thank you very much! I just assigned my plugin notes to the settings. ;-)

Even unicode characters and html entities &#128293; work:

![image](https://github.com/alberti42/obsidian-plugins-annotations/assets/4138869/fe6c4e56-7bbc-4d26-a67e-ac53d21c8571)

Here is a suggestion:

Is it possible for the links to be renamed automatically when the file name is changed? Like in other places of Obsdian?

**Comment by alberti42** [comment]
> Is it possible for the links to be renamed automatically when the file 
> name is changed? Like in other places of Obsdian?

Unfortunately, this does not happen automatically. I was thinking about 
it. It is not super simple to implement. To leverage Obsidian auto 
rename feature, we would need to create a proper .md note containing all 
annotations in some "Meta" folder in the vault. Then, my plugin imports 
the annotation form that .md note and Obsidian is able to do its job.

The other possibility is hack in the core of Obsidian and trig an auto 
rename of the links, but this requires manually to rename the links and 
it is much more prone to break in the future.

**Comment by merlinuwe** [comment]
It is enough for me that you considered it and I can understand that the effort is against it.

I am already glad that the basic function is there. Today I have further renamed my plugin comments systematically in [[Plugin - name of the plugin]] and assigned them. I also worked directly in the data.json.

Thank you again for this very useful plugin. ;-)

**Comment by alberti42** [comment]
We close the thread. The basic feature has been implemented. In the future, an improvement will be automatically to update the links when the notes get renamed.

**Comment by alberti42** [comment]
In the new version 1.5.0, you can now provide a .md file in your vault containing the annotations. In this way, links are getting automatically updated if you rename one of the linked files in your vault.

**Comment by merlinuwe** [comment]
I am very happy about this extension, thank you very much.
