### ISSUE TITLE
[FR] Customize the default text "Add to plugin xx..."

### ISSUE THREAD

**Issue by Moyf** [alberti42/obsidian-plugins-annotations#4]
Hey! Good to see the updates, and I've tried the new Function to auto hide the "Add.." text.
However, this will cause the plugin flash when my mouse move over.

I'm wondering could you consider adding the customization for default "Add..." text, just like the labe?
![image](https://github.com/alberti42/obsidian-plugins-annotations/assets/4013062/0815bccd-52f5-4b49-9bb4-53fb6d9c3f19)

So that I can set the default text shorter, meanwhile showing 'em to edit  : )

**Comment by alberti42** [comment]
Thanks for the feedback!

By flashing, you mean that suddenly the annotation field appears? This 
was the intended behavior. However, I can see that it can be annoying to 
some.

I added the feature because I wanted to have an interface that is not 
cluttered. Your suggestion of adding buttons is doable and quite 
straightforward to implement. However, I am afraid this would make the 
whole interface more cluttered than just showing the placeholders where 
to add the annotation.

I am thinking of another toggle that makes the field in "Community 
plugins" not editable and hide those empty. Once you finished editing 
your plugins, you can turn the toggle on, which basically protects the 
annotations from being erroneously changed.

A bit more demanding, but also doable is to offer a second way to enter 
the annotations from the setting pane for each installed plugin. Then 
one does not need to edit in the `community plugins` pane.

Let me know what you think.

Best

**Comment by Moyf** [comment]
> Thanks for the feedback! By flashing, you mean that suddenly the annotation field appears? This was the intended behavior. However, I can see that it can be annoying to some. I added the feature because I wanted to have an interface that is not cluttered. Your suggestion of adding buttons is doable and quite straightforward to implement. However, I am afraid this would make the whole interface more cluttered than just showing the placeholders where to add the annotation. I am thinking of another toggle that makes the field in "Community plugins" not editable and hide those empty. Once you finished editing your plugins, you can turn the toggle on, which basically protects the annotations from being erroneously changed. A bit more demanding, but also doable is to offer a second way to enter the annotations from the setting pane for each installed plugin. Then one does not need to edit in the `community plugins` pane. Let me know what you think. Best
> […](#)
> Hey! Good to see the updates, and I've tried the new Function to auto hide the "Add.." text. However, this will cause the plugin flash when my mouse move over. I'm wondering could you consider adding the customization for default "Add..." text, just like the labe? ![image](https://github.com/alberti42/obsidian-plugins-annotations/assets/4013062/0815bccd-52f5-4b49-9bb4-53fb6d9c3f19) So that I can set the default text shorter, meanwhile showing 'em to edit : ) -- Reply to this email directly or view it on GitHub: #4 You are receiving this because you are subscribed to this thread. Message ID: ***@***.***>

I can live with some short default text like just *Edit* LOL

Though, I agree that adding button would make the UI more cluttered.  In comparison, a right click context menu might be less cluttered? You only click in the plugin to show the "Add annotation" menu,  and otherwise, you wouldn't see any placeholder thing.
*But I'm not sure if it would be hard to integrate it*

The idea of a **Edit Mode** switch sounds reasonable. I can imagine how it works like.. click a button to start editing, and click it again to lock all the annotations and hide the empty placeholder.
![image](https://github.com/alberti42/obsidian-plugins-annotations/assets/4013062/05fe364b-63d8-4818-be3f-dba5b6fca502)
This approach would also work for me!

Oh and I have to say this plugin is really creative and useful, LOVE IT. Thanks for your development! <3


---

Off-topic, I personally want to recommend another plugin for managing plugins - because I am currently using them together. 

This plugin is called [Settings Management](https://github.com/xhuajin/obsidian-settings-management), which allows you to change the display style of plugins (card layout), show only enabled or disabled plugins, and save the enabled plugin configuration for easy switching. If you are interested, I recommend you give it a try too!  ; )
![image](https://github.com/alberti42/obsidian-plugins-annotations/assets/4013062/9bdf2bf3-b51c-48f8-8168-0c915b1bfd0b)

**Comment by alberti42** [comment]
Thanks for pointing out the other plugin. It seems interesting, though, I was not sure how to use it.

I was indeed planning to have a new simple plugin allowing one to switch between two configurations for the enabled plugins, one called "Tests" and the other "Production". We often test many plugins for fun, but when we have to work, we like to focus on what it works. Moreover, sometimes there are bugs in some plugin and one has to find it out by exclusion. It is nice if one can store the configuration of the installed plugins and restore it at the right time.

Do you think the plugin "Settings Management" can do this?

**Comment by alberti42** [comment]
PS: I released a new version of my plugin with a lock button. It should be easy to locate. You can lock the annotations and avoid the "flashing" you mentioned.

**Comment by alberti42** [comment]
And you can customize the default text with any HTML you want, or simple text. Go in the preference pane of my plugin.

**Comment by Moyf** [comment]
> Thanks for pointing out the other plugin. It seems interesting, though, I was not sure how to use it.
> 
> I was indeed planning to have a new simple plugin allowing one to switch between two configurations for the enabled plugins, one called "Tests" and the other "Production". We often test many plugins for fun, but when we have to work, we like to focus on what it works. Moreover, sometimes there are bugs in some plugin and one has to find it out by exclusion. It is nice if one can store the configuration of the installed plugins and restore it at the right time.
> 
> Do you think the plugin "Settings Management" can do this?

Yeah, I think it could do this!

After installing this plugin, it would show a toolbar in your **Community Plugins**  pages:
![image](https://github.com/alberti42/obsidian-plugins-annotations/assets/4013062/4a5a6b6f-e797-4fd1-8791-2cba9ded7b08)

Use the third button to store a preset of Plugins you enabled, and after that , use the forth button to restore into a preset.

(the 1st and 2nd buttons are for the view, 1st could switch between "Show all plugins / Show only enbled plugins / Show only disabled plugins", 2nd button can use grid view for plugins

**Comment by Moyf** [comment]
> PS: I released a new version of my plugin with a lock button. It should be easy to locate. You can lock the annotations and avoid the "flashing" you mentioned.

Just updated and tested it, works great! Thanks!

![image](https://github.com/alberti42/obsidian-plugins-annotations/assets/4013062/6c322088-e06e-42e8-bbbd-4f5ca54a64c9)
But sometimes there are 2 lock buttons 🤔

**Comment by alberti42** [comment]
Ok. I thought I solved the problem of the two locks. If you see how to 
reproduce it, it would be nice if you can describe it.

Basically, if you trigger a second time the pane, and the plugin 
believes it is the first time showing it, it draws this again.

But I don't see this problem on my devices anymore.

**Comment by Moyf** [comment]
> Ok. I thought I solved the problem of the two locks. If you see how to reproduce it, it would be nice if you can describe it. Basically, if you trigger a second time the pane, and the plugin believes it is the first time showing it, it draws this again. But I don't see this problem on my devices anymore.
> […](#)
> > PS: I released a new version of my plugin with a lock button. It > should be easy to locate. You can lock the annotations and avoid the > "flashing" you mentioned. Just updated and tested it, works great! Thanks! ![image](https://github.com/alberti42/obsidian-plugins-annotations/assets/4013062/6c322088-e06e-42e8-bbbd-4f5ca54a64c9) But sometimes there are 2 lock buttons 🤔 -- Reply to this email directly or view it on GitHub: [#4 (comment)](https://github.com/alberti42/obsidian-plugins-annotations/issues/4#issuecomment-2208416526) You are receiving this because you commented. Message ID: ***@***.***>

Tried to re-produce the issue.
For me, just switch to another tab and switch back to Community Plugins tab, the lock icon would be doubled:
![demo](https://github.com/alberti42/obsidian-plugins-annotations/assets/4013062/1f5b9a8a-ec48-43c7-8b51-aa9b5da0ef6b)

---

And I found another problem that if I search the Plugin, the annotation placeholder would be lost.
![demo2](https://github.com/alberti42/obsidian-plugins-annotations/assets/4013062/dbc32ddd-cadd-491b-af32-b17f76a3189c)

**Comment by alberti42** [comment]
Thanks for replying. Are you running the latest version or perhaps some 
old version you installed from GitHub?

I will test the plugin on more devices. But perhaps it is the 
interaction with some other plugin?

The basic point is that the plugin is informed when the community 
plugins pane is opened. Then it checks whether this was already opened 
before. If not it draws the lock. Apparently it does not detect 
correctly that the pane was opened before.

If the problem persists I will try a different approach.
