### ISSUE TITLE
Clarify how to use the preamble

### ISSUE THREAD

**Issue by gkavboy** [alberti42/obsidian-plugins-annotations#6]
When I tried to set up the `html:` or `markdown:` preamble, I couldn’t figure out how it was set up for a long time until I got into the code.
Add to the description that the preamble should be placed on the first line, the rest of the text on the second and subsequent lines:
![image](https://github.com/user-attachments/assets/48b62cf0-b560-487e-b3e9-4db2c88fdf15)

**Comment by alberti42** [comment]
Thanks for the comment! I will add the explanation!

**Comment by alberti42** [comment]
In the new version 1.5.0, the first line determining the type of annotation is automatically shown when editing the annotation.

I also changed the instructions in the preferences' pane.

**Comment by alberti42** [comment]
I believe the issue is now solved. Markdown (which can include html code) is now the default way to enter annotations. Feel free to reopen it if you think there is something to be added.
