### ISSUE TITLE
latest update broken, cannot find ID

### ISSUE THREAD

**Issue by ksdavidc** [alberti42/obsidian-plugins-annotations#7]
somehow after latest update, I am getting message that it can't find the id. New annotations made in the settings pane do not appear. In one of my vaults, no error appears, otherwise:

```
plugin:plugins-annotations:2295 Plugin ID not found for plugin name: Admonition
addAnnotation @ plugin:plugins-annotations:2295
eval @ plugin:plugins-annotations:2045
wrapper @ plugin:plugins-annotations:64
t.updateSearch @ app.js:1
t.render @ app.js:1
t.display @ app.js:1
eval @ plugin:obsidian-divide-and-conquer:1543
plugin:plugins-annotations:2295 Plugin ID not found for plugin name: Admonition
addAnnotation @ plugin:plugins-annotations:2295
eval @ plugin:plugins-annotations:2045
wrapper @ plugin:plugins-annotations:64
t.updateSearch @ app.js:1
t.render @ app.js:1
t.display @ app.js:1
eval @ plugin:obsidian-divide-and-conquer:1543
plugin:plugins-annotations:2295 Plugin ID not found for plugin name: Admonition
addAnnotation @ plugin:plugins-annotations:2295
eval @ plugin:plugins-annotations:2045
wrapper @ plugin:plugins-annotations:64
t.updateSearch @ app.js:1
t.render @ app.js:1
t.display @ app.js:1
eval @ plugin:obsidian-divide-and-conquer:1543
plugin:plugins-annotations:2295 Plugin ID not found for plugin name: Admonition
addAnnotation @ plugin:plugins-annotations:2295
eval @ plugin:plugins-annotations:2320
addAnnotations @ plugin:plugins-annotations:2319
await in addAnnotations (async)
observeTab @ plugin:plugins-annotations:2062
eval @ plugin:plugins-annotations:2009
wrapper @ plugin:plugins-annotations:64
t.openTabById @ app.js:1
eval @ plugin:settings-search:295
wrapper @ plugin:settings-search:59
setting.onOpen @ plugin:settings-management:68
eval @ plugin:settings-search:256
wrapper @ plugin:settings-search:59
e.open @ app.js:1
callback @ app.js:1
BK @ app.js:1
e.executeCommand @ app.js:1
eval @ plugin:obsidian-kanban:67
o @ plugin:obsidian-kanban:33
e.executeCommandById @ app.js:1
eval @ plugin:obsidian-doubleshift:267
doubleshift @ plugin:obsidian-doubleshift:260
eval @ plugin:obsidian-doubleshift:256
plugin:plugins-annotations:2295 Plugin ID not found for plugin name: Advanced Paste
addAnnotation @ plugin:plugins-annotations:2295
eval @ plugin:plugins-annotations:2320
addAnnotations @ plugin:plugins-annotations:2319
await in addAnnotations (async)
observeTab @ plugin:plugins-annotations:2062
eval @ plugin:plugins-annotations:2009
wrapper @ plugin:plugins-annotations:64
t.openTabById @ app.js:1
eval @ plugin:settings-search:295
wrapper @ plugin:settings-search:59
setting.onOpen @ plugin:settings-management:68
eval @ plugin:settings-search:256
wrapper @ plugin:settings-search:59
e.open @ app.js:1
callback @ app.js:1
BK @ app.js:1
e.executeCommand @ app.js:1
eval @ plugin:obsidian-kanban:67

etc...
```
[obsidian.md-1723582431775.log](https://github.com/user-attachments/files/16605201/obsidian.md-1723582431775.log)

Reverting to previous version works again, though I almost lost my annotations. Luckily, I had made an .md file before noticing the problem :)

**Comment by alberti42** [comment]
Thanks for the feedback!

I worked a lot to ensure that annotations are not getting lost and upgraded to the new format. Obviously, I missed something.

Would you be so kind to send me your `data.json` file. You can find it under the folder `YOUR_VAULT/.obsidian/plugins/plugins-annotations`. This will allow me to understand what went wrong and fix it.

**Comment by alberti42** [comment]
Meanwhile, I withdrew the release 1.5.0 until I will figure out what went wrong with your settings. I want to avoid endangering the annotations of other users.

**Comment by ksdavidc** [comment]
Good luck. 

In this particular vault, no error was thrown.

[data.json](https://github.com/user-attachments/files/16605714/data.json)

https://github.com/user-attachments/assets/341fa371-ac4b-483a-8528-111beb32c171

**Comment by ksdavidc** [comment]
> Meanwhile, I withdrew the release 1.5.0 until I will figure out what went wrong with your settings. I want to avoid endangering the annotations of other users.

The losing of the annotations was my fault, for uninstalling. I don't think the plugin as it was lost any.

**Comment by alberti42** [comment]
Thank you! 

> The losing of the annotations was my fault, for uninstalling. I don't think the plugin as it was lost any.

This is very helpful to know. Yes, indeed, this is a typical thing of Obsidian. If you uninstall a plugin, you lose all important settings stored in the plugin. I will consider in the future adding a button to make a backup of the configurations and settings.

**Comment by alberti42** [comment]
You said you could recover your old annotations. Could you send me this `data.json`? The one you sent me contains no annotations. If you open it, you would find:

```
{
  "annotations": {},
  "plugins_annotations_uuid": "BC56AB7B-A46F-4ACF-9BA1-3A4461F74C79",
  "hide_placeholders": false,
  "delete_placeholder_string_on_insertion": false,
  "label_mobile": "<b>Annotation:&nbsp;</b>",
  "label_desktop": "<b>Personal annotation:&nbsp;</b>",
  "label_placeholder": "<em>Add your personal comment about <strong>${plugin_name}</strong> here...</em>",
  "editable": true,
  "automatic_remove": false,
  "markdown_file_path": "",
  "compatibility": "1.5.0"
}
```

The first field `annotations` should not be just empty `{}` as in your case, but contain a list of annotations. If you can find your data.json file that has worked until now and still works with the previous version, it will be super helpful to debug and fix the problem.

**Comment by ksdavidc** [comment]
Here is your rabbit hole.

I found an old vault that had the veresion 1.4 installed: 
```
{
  "annotations": {
    "mrj-crosslink-between-notes": {
      "anno": "another test",
      "name": "Add links to current note"
    }
  },
  "plugins_annotations_uuid": "B265C5B2-A6AD-4194-9E4C-C1327DB1EA18",
  "hide_placeholders": false,
  "delete_placeholder_string_on_insertion": false,
  "label_mobile": "<b>Annotation:&nbsp;</b>",
  "label_desktop": "<b>Personal annotation:&nbsp;</b>",
  "label_placeholder": "<em>Add your personal comment about <strong>${plugin_name}</strong> here...</em>",
  "editable": true,
  "automatic_remove": false
}
```

so I pasted the annotations part into a vault that had 1.5 installed and was missing the annotation (but had the same plugin):

```
{
  "annotations": {
    "mrj-crosslink-between-notes": {
      "anno": "another test",
      "name": "Add links to current note"
      "type": "markdown"
    }
  },
  "plugins_annotations_uuid": "BC56AB7B-A46F-4ACF-9BA1-3A4461F74C79",
  "hide_placeholders": false,
  "delete_placeholder_string_on_insertion": false,
  "label_mobile": "<b>Annotation:&nbsp;</b>",
  "label_desktop": "<b>Personal annotation:&nbsp;</b>",
  "label_placeholder": "<em>Add your personal comment about <strong>${plugin_name}</strong> here...</em>",
  "editable": true,
  "automatic_remove": false,
  "markdown_file_path": "_newtest.md",
  "compatibility": "1.5.0"
}
```

This annotation appears properly, and is editable. If I edit it, the edits appear in the file (I can monitor the contents of the file in a text editor).

However, I am not able to make edits to any other plugins that stick.

Now, if I try to switch to markdown as the markdown file **(in the root directory)**, and add a new file, the plugin settings show the new file, but no new file is created. 

```
{
  "annotations": {
    "mrj-crosslink-between-notes": {
      "desc": "this is a test of it youu",
      "name": "Add links to current note",
      "type": "markdown"
    }
  },
  "plugins_annotations_uuid": "BC56AB7B-A46F-4ACF-9BA1-3A4461F74C79",
  "hide_placeholders": false,
  "delete_placeholder_string_on_insertion": false,
  "label_mobile": "<b>Annotation:&nbsp;</b>",
  "label_desktop": "Personal annotation",
  "label_placeholder": "Add your personal comment ",
  "editable": true,
  "automatic_remove": false,
  "markdown_file_path": "anewtest.md",
  "compatibility": "1.5.0"
}
```


Switching to subdirectory is okay:

```
{
  "annotations": {
    "mrj-crosslink-between-notes": {
      "desc": "this is a test of it youu",
      "name": "Add links to current note",
      "type": "markdown"
    }
  },
  "plugins_annotations_uuid": "BC56AB7B-A46F-4ACF-9BA1-3A4461F74C79",
  "hide_placeholders": false,
  "delete_placeholder_string_on_insertion": false,
  "label_mobile": "<b>Annotation:&nbsp;</b>",
  "label_desktop": "Personal annotation",
  "label_placeholder": "Add your personal comment ",
  "editable": true,
  "automatic_remove": false,
  "markdown_file_path": "temp/anewtest.md",
  "compatibility": "1.5.0"
}
```
```

Make changes only within the annotation blocks marked by <!-- BEGIN ANNOTATION --> and <!-- END ANNOTATION -->. Changes made anywhere else will be overwritten.

# Add links to current note

<!-- id: mrj-crosslink-between-notes -->
<!-- BEGIN ANNOTATION -->
this is a test of it youu
<!-- END ANNOTATION -->

```

This is editable both from settings and from the file.

HOwever, edits from teh file do NOT appear in the json file ***until I edit it from settings!**


Edting in other plugins still does not work.

**Comment by ksdavidc** [comment]
I recovered the content of the edits from the markdown file, but not the contents of the json, so I can't send you the json.

**Comment by alberti42** [comment]
Thanks a lot for the detailed feedback. It was very useful to identify two bugs.

After your feedback, I added to version 1.5.1 a section for managing backups of the annotations. I don't want people to lose their annotations because something goes wrong.

**Comment by ksdavidc** [comment]
Dang, it works! 

Great job, thanks for fixing it so promptly. I am looking forward to making good use of it!

:-)

**Comment by alberti42** [comment]
Thank you very much for your quick feedback and help identifying the problems. It was super helpful. I will close this issue.
