### ISSUE TITLE
Cannot install 1.6.2

### ISSUE THREAD

**Issue by merlinuwe** [alberti42/obsidian-plugins-annotations#9]
Even not if I uninstall the previous release.

![image](https://github.com/user-attachments/assets/20e1a9b5-6d8d-4979-8491-0396bacfa3b7)

**Comment by alberti42** [comment]
Thanks a lot for the feedback. I am not sure why it happened. I just released version 1.6.2 right now (see https://github.com/alberti42/obsidian-plugins-annotations/releases/tag/1.6.2).

Possibly Obsidian already detects new versions when I commit a new manifest with the increased version number. However, it can only work after I make a new released based on that version.

I expect that the installation will now work for you.

**Comment by merlinuwe** [comment]
Works again, tested with android 11.

**Comment by merlinuwe** [comment]
Thank you very much.
